### ISSUE TITLE
Not compatible with netstandard2.0

### ISSUE THREAD

**Issue by dylanvdmerwe** [Tornhoof/SpanJson#104]
I get the following error when trying to add this package to my project:
```
NU1202	Package SpanJson 2.0.4 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package SpanJson 2.0.4 supports: netcoreapp2.1 (.NETCoreApp,Version=v2.1)	
```

Is there any reason why this lib targets netcoreapp2.1 and cannot target netstandard2.0?

**Comment by Tornhoof** [comment]
Yes, a few of the utf8formatters/parsers, several helper apis like ``RuntimeHelpers.IsReferenceOrContainsReferences<T>()`` are not available in .net standard.
If you need a .net Standard 2.0 compatible library I recommend looking at Utf8json and/or Jil, both have a similar performance.
