### ISSUE TITLE
RegisterGlobalCustomFormatter and arrays

### ISSUE THREAD

**Issue by tadeuszwojcik** [Tornhoof/SpanJson#108]
Hi,
Is there a way to implement ICustomJsonFormatter that would serialize/deserialize arrays in custom way and register it via 
`RegisterGlobalCustomFormatter `  ? I did that without issues for custom enum formatter, but had not luck with arrays.

**Comment by Tornhoof** [comment]
Do you need specific behavior only for Arrays? 
That is not properly  supported, if you just need Array support you should register the non-array version, this one is then used together with the normal array formatter.

**Comment by tadeuszwojcik** [comment]
I see, thanks for clarification.
