### ISSUE TITLE
Serialize Enum as int

### ISSUE THREAD

**Issue by hez2010** [Tornhoof/SpanJson#112]
Currently the behavior of serializing Enum is to convert it to string. However I think Enums should be serialized to int.

**Comment by Tornhoof** [comment]
Thank you for your question.
You can control that yourself, by creating a CustomFormatter as described in the Readme. In this example the enumOption is set to Integer.
```csharp
public sealed class CustomResolver<TSymbol> : ResolverBase<TSymbol, CustomResolver<TSymbol>> where TSymbol : struct
{
    public CustomResolver() : base(new SpanJsonOptions
    {
        NullOption = NullOptions.ExcludeNulls,
        NamingConvention = NamingConventions.CamelCase,
        EnumOption = EnumOptions.Integer
    })
    {
    }
}
```

**Comment by hez2010** [comment]
Thanks.
But I think serializing Enum as Integer should be a default behavior because the value of an enum can be an integer which is undefined.

**Comment by Tornhoof** [comment]
You mean when you serialize/deserialize an integer to an enum which is not part of your enum declaration, i.e. you have an enum with ordinal values 1 and 2 and you suddenly receive 4?
I consider this an error, as I consider enums for data transfer to be part of the interface contract.

**Comment by hez2010** [comment]
Thanks.
