### ISSUE TITLE
[Question] JSON Constructor - can it be private?

### ISSUE THREAD

**Issue by dazinator** [Tornhoof/SpanJson#113]
I am wondering whether a JSONConstructor attribute will work with a private constructor?

The use case is that I have some business objects, that have non default constructors. In the ordinary case, when constructing the business object, these are the public constructors that should be used.

However if I want to allow the serialiser to be able to construct the business object during deserialisation, the fact that it doesn't have a public default constructor is problematic - meaning I must add a constructor to support the serialiser, and annotate it with the JSONConstructor attribute. This would work fine, but I would prefer not to expose this constructor in the public API as it shouldn't be used in the ordinary case of working with the business object.

**Comment by Tornhoof** [comment]
Hello,
thank you for your interest in SpanJson.
Currently, the attribute works only on public constructors.
https://github.com/Tornhoof/SpanJson/blob/c9783e24b2f374997b43e6fd14c16b273338ac29/SpanJson/Resolvers/ResolverBase.cs#L199-L203

I understand your point, but how do you create your business objects, if you don't do serialization?
Some kind of factory?

In general SpanJson is designed to be used with specially crafted data objects.

**Comment by dazinator** [comment]
> how do you create your business objects, if you don't do serialization

Yes, typically use factory methods as we use the CSLA.NET framework for a business tier and this is the preferred pattern as object creation is routed through it's data-portal which means the object can actually be created on another application server rather than the locally running application if CSLA is configured to use one.

Is it possible to make this constructor selection overrideable able so I could implement my own logic here to include private?

**Comment by Tornhoof** [comment]
Yeah, that's the best idea I have at the moment, make some of the methods protected virtual, so you can override them and handle it yourself.

**Comment by Tornhoof** [comment]
This should work now, see for example:
https://github.com/Tornhoof/SpanJson/blob/877777566c1576de00e3cac5422d8e6623cc560c/SpanJson.Tests/ConstructorAttributeTests.cs#L320-L376

**Comment by dazinator** [comment]
Brilliant, thanks for enabling this.
