### ISSUE TITLE
DeserializeAsync method can support length parameter?

### ISSUE THREAD

**Issue by IKende** [Tornhoof/SpanJson#114]
I'm deserialize async  from network stream,but the stream tail non-JSON data cannot be interpreted successfully,i don't want to copy the network stream to memory.

**Comment by Tornhoof** [comment]
The current DeserializeAsync copies the stream to memory anyway, so if you know the length you can wrap the stream in some kind of length-limiting stream and make sure that the stream returns only the valid JSON data.
