### ISSUE TITLE
Array not returned to the array pool when an exception is thrown during serialization

### ISSUE THREAD

**Issue by LeroyK** [Tornhoof/SpanJson#124]
When an exception is thrown during serialization, the rented array is never returned to the array pool.

My suggestion to fix this:
1. Make ``JsonWriter<TSymbol>.Dispose()`` public. Don't make it internal, because others who use the type should also be able to call ``Dispose()``.
2. Remove the implicit dispose in ``JsonWriter<TSymbol>.ToString()``.
3. Use try-finally everywhere ``JsonWriter<TSymbol>`` is used and call ``Dispose()`` in the finally block.

**Comment by Tornhoof** [comment]
As errors during writing should be rare, for high performance code the normal approach apparently is simply to let it throw as the GC will then sooner or later take care of the array.
But the idea gets more interesting with c#8 and dispose via using without the interface.

**Comment by Tornhoof** [comment]
I will look into this closer for the 3.0 version of SpanJson, until then I recommend to either ignore it and let the GC do it or call ToString() if possible.

**Comment by Tornhoof** [comment]
Your suggestions are implemented now in 3.0, there are still some cases probably where an exception might not release the arraypool, but that's then handled by GC. All the relevant cases in the serialize are covered.
