### ISSUE TITLE
Custom formatter not called

### ISSUE THREAD

**Issue by vitidev** [Tornhoof/SpanJson#126]
I don't understand. I create new dotnetcore 2.2 project (cli) and copy code from [test ](https://github.com/Tornhoof/SpanJson/blob/master/SpanJson.Tests/CustomSerializerTests.cs)

    [JsonCustomSerializer(typeof(TwcsCustomSerializer))]
    public class TypeWithCustomSerializer : IEquatable<TypeWithCustomSerializer>
    {
        public long Value { get; set; }

        public bool Equals(TypeWithCustomSerializer other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;
            return Value == other.Value;
        }

        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj is TypeWithCustomSerializer twcs && Equals(twcs);
        }

        public override int GetHashCode()
        {
            // ReSharper disable once NonReadonlyMemberInGetHashCode
            return Value.GetHashCode();
        }
    }

    public sealed class TwcsCustomSerializer : ICustomJsonFormatter<TypeWithCustomSerializer>
    {
        public static readonly TwcsCustomSerializer Default = new TwcsCustomSerializer();

        public object Arguments { get; set; }

        private void SerializeInternal<TSymbol>(ref JsonWriter<TSymbol> writer, TypeWithCustomSerializer value)
            where TSymbol : struct
        {
            if (value == null)
            {
                writer.WriteNull();
                return;
            }

            writer.WriteBeginObject();

            writer.WriteName(nameof(TypeWithCustomSerializer.Value));

            writer.WriteInt64(value.Value);

            writer.WriteEndObject();
        }

        public void Serialize(ref JsonWriter<byte> writer, TypeWithCustomSerializer value)
        {
            SerializeInternal(ref writer, value);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private TypeWithCustomSerializer DeserializeInternal<TSymbol>(ref JsonReader<TSymbol> reader)
            where TSymbol : struct
        {
            if (reader.ReadIsNull())
            {
                return null;
            }

            reader.ReadBeginObjectOrThrow();
            var result = new TypeWithCustomSerializer {Value = reader.ReadInt64()};
            reader.ReadEndObjectOrThrow();
            return result;
        }

        public TypeWithCustomSerializer Deserialize(ref JsonReader<byte> reader)
        {
            return DeserializeInternal(ref reader);
        }

        public void Serialize(ref JsonWriter<char> writer, TypeWithCustomSerializer value)
        {
            SerializeInternal(ref writer, value);
        }

        public TypeWithCustomSerializer Deserialize(ref JsonReader<char> reader)
        {
            return DeserializeInternal(ref reader);
        }
    } 
    
    internal class Program
    {
        private static void Main(string[] args)
        {
            var serialized = "{\"Value\":100}";
            var obj = JsonSerializer.Generic.Utf16.Deserialize<TypeWithCustomSerializer>(serialized);
            Debug.Assert(obj.Value == 100);
        }
    }

And set breakpoint to all methods. And no any breakpoint was hit. 
Also I replace all methods to  throw new NotImplementedException(); and I still get successful deserialization

**Comment by Tornhoof** [comment]
Thank you for reporting this issue.
I can confirm that it is not calling the type.
I'm not sure that it ever worked properly, the tests responsible for it are basically just testing the normal behaviour without the formatter.

**Comment by Tornhoof** [comment]
This should be fixed in 2.0.11

**Comment by vitidev** [comment]
It is also a pity that the formatter cannot be passed as a parameter to Deserialize<>.

**Comment by Tornhoof** [comment]
Yeah, at-runtime override of the formatter does not work properly if the whole chain is prebuild.
