### ISSUE TITLE
custom serializer example

### ISSUE THREAD

**Issue by vitidev** [Tornhoof/SpanJson#128]
simplified json example

    {
       "num_results": 3,
       "more_available": false,
       "status": "ok"
     }

and parse it with custom serializer
as I understand it, I can't do something like that

    internal class ResponseDataConverter : JsonConverter
    {
        public override bool CanConvert(Type objectType)
        {
            return objectType == typeof(MyResponse);
        }

        public override object ReadJson(JsonReader reader,
            Type objectType,
            object existingValue,
            JsonSerializer serializer)
        {
            var token = JToken.Load(reader);
            var resp= token.ToObject<MyResponse>();
            var items = token["ext_items"];
           // combine resp and items with complex rules
            ....

and must use ONLY "flow" parsing, right? But how?

        public MyResponse Deserialize(ref JsonReader<char> reader)
        {
            if (reader.ReadIsNull())
            {
                return null;
            }
            reader.ReadBeginObjectOrThrow();
            var name = reader.ReadEscapedName(); //num_results
            var val = reader.ReadInt32(); //3

            //reader.ReadNextToken();

            var name1 = reader.ReadEscapedName(); //SpanJson.JsonParserException: 'Error Reading JSON data: 'ExpectedDoubleQuote' at position: '22'.'
            var val2 = reader.ReadInt32(); 
           ...
        }
I can't read next value: "more_available": false,

**Comment by Tornhoof** [comment]
Yeah, the reader at that moment is on the value separator.
So you'd need to skip the next token, which is kinda ugly at the moment like ``               reader.SkipNextUtf16Value(reader.ReadNextToken());`` (or depending on utf8/utf16).

If you want to read a full object, I recommend something like this, loop through the values and parse it fully.
https://github.com/Tornhoof/SpanJson/blob/fc7f676ad9026eecaf9ffaf04b189177722a6632/SpanJson.Tests/JsonReaderTests.cs#L14-L36

**Comment by vitidev** [comment]
1 what is "count" in

     !reader.TryReadUtf16IsEndObjectOrValueSeparator(ref count)

2 ".ToString()" make allocation
What is the point of getting a span and then make allocation anyway? how to avoid it?

**Comment by Tornhoof** [comment]
The ToString is just an example in the source, take the Span and sequenceEqual to an Array of Symbols would be the obvious way.
Count is used to find out if a value separater is actually valid at that Position.

In general, I would not recommend writing your own custom formatters. If you really need dynamic Data, take a look at the dynamic Support or ``JsonExtensionData``.

**Comment by vitidev** [comment]
there is a very large and very complex json structure with nested classes and you only need part of the fields. In this case, `Deserialize<>` will make many useless allocations.

But in case of custom deserialization is very necessary
      
      reader.ReadObject<SomeClass>() 

which read data from current { or [ till closed braces and return structrure

On top level I can do `...Deserialize<SomeClass>`, but not with reader

**Comment by Tornhoof** [comment]
Ah ok. I highly recommend to simply create appropriate objects with only the fields you use, SpanJson is fairly efficient in skipping unused parts of the json. Doing it manually, even with SkipSegment will probably not be faster.

**Comment by vitidev** [comment]
> SpanJson is fairly efficient in skipping unused parts of the json.

Not in this case

    {
      "num_results": 3,
      "more_available": false,
      "items": [
        {
          "need_key": { "id": 1 },
          "not_needed_key": ...,
          "not_needed_key": ...,
        },
        {
          "need_key": {"id": 2},
          "not_needed_key": ...,
          "not_needed_key": ...,
        },
        {
          "need_key": { "id": 3 },
          "not_needed_key": ...,
          "not_needed_key": ...,
        }
      ],
      "status": "ok"
    }

and       

        [DataMember(Name = "items")]
        public IList<Dictionary<string, Item>> Items { get; set; }

unused parts of json will not be skipped and all objects with dictionary "not_needed_key" will be created

**Comment by Tornhoof** [comment]
Yeah, you obviously need to know the keys you want and instead of Dictionary<...> you have a proper type.

**Comment by vitidev** [comment]
> you have a proper type.

Not understood. What type? All dictionaries values are `Item` but not full dictionary is needed (in general, the dictionary is not needed, there is extraction values by known key and flatten to single IList<Item>)

**Comment by Tornhoof** [comment]
Instead of having IList<Dictionary<string, Item>>, you use IList<MyCustomType>, where MyCustomType looks something like this:
```csharp
public class MyCustomType
{
    [DataMember(Name = "need_key")]
    public Item NeedKey {get;set;}
    [DataMember(Name = "need_key2")]
    public Item NeedKey2 {get;set;}
}
```

**Comment by vitidev** [comment]
LOL. You are right.

I port the code where  dictionary used in this place and did not even notice that it is a proper type

Of course, so I get an extra allocation of `MyCustomType`, but do not get extra allocations of `Item`

**Comment by Tornhoof** [comment]
There is probably not much difference in allocations, the dictionary is a class too, so you get the same allocations as with mycustomtype.
