### ISSUE TITLE
Why SpanJson.AspNetCore.Formatter require empty constructor?

### ISSUE THREAD

**Issue by vitidev** [Tornhoof/SpanJson#129]
action 

    [HttpGet]
    public async Task<IList<Group>> Get(CancellationToken ct)
    {
        var items = await _db.Query<Group>().AllAsync(ct);
        return items;
    }

Group 

    [UseDto(typeof(GroupDto))]
    public class Group : Entity
    {
        public Group(string name, string info = null)
        {
            Name = name;
            Info = info;
        }

        public string Name { get; }

        public string Info { get; }
    }

Error

    An unhandled exception occurred while processing the request.
    ArgumentException: Type 'Core.Models.Group' does not have a default constructor
    Parameter name: type

    System.Linq.Expressions.Expression.New(Type type)
    TypeInitializationException: The type initializer for 'SpanJson.Formatters.ComplexClassFormatter`3' threw an exception.

    System.Linq.Expressions.Expression.New(Type type)
    TargetInvocationException: Exception has been thrown by the target of an invocation.

    System.RuntimeFieldHandle.GetValue(RtFieldInfo field, object instance, RuntimeType fieldType, RuntimeType declaringType, ref bool domainInitialized)
    TypeInitializationException: The type initializer for 'SpanJson.Formatters.ListFormatter`4' threw an exception.

    System.RuntimeFieldHandle.GetValue(RtFieldInfo field, object instance, RuntimeType fieldType, RuntimeType declaringType, ref bool domainInitialized)
    TargetInvocationException: Exception has been thrown by the target of an invocation.

    System.RuntimeFieldHandle.GetValue(RtFieldInfo field, object instance, RuntimeType fieldType, RuntimeType declaringType, ref bool domainInitialized)
    TypeInitializationException: The type initializer for 'Inner`3' threw an exception.

    lambda_method(Closure , object , Stream , CancellationToken )

SpanJson.AspNetCore.Formatter == only serialize to string. So why we need empty contructor?

**Comment by Tornhoof** [comment]
Because both serializer and deserializer are constructed at the same time.

**Comment by OlsonDev** [comment]
This requirement is a bit absurd. It's super common for apps to have objects that are intended to be used as "incoming" and those that are intended to be outgoing. If I have an outgoing one, I'm never going to have to deserialize it.
