### ISSUE TITLE
Incorrect flags enum serialization

### ISSUE THREAD

**Issue by vitidev** [Tornhoof/SpanJson#130]
Code

    public class Item
    {
        public MyEnum Enum { get; set; }
    }

    [Flags]
    public enum MyEnum
    {
        One = 1,
        Two = 2
    }
    class Program
    {
        static void Main(string[] args)
        {
            var item = new Item();

            var spanJson = JsonSerializer.Generic.Utf16.Serialize(item);
            var json = JsonConvert.SerializeObject(item);
        }
    }

spanJson 

    {"Enum":""}

json 

    {"Enum":0}

I think that Newtonsoft does more correctly, because the value 0 is also a flag.

**Comment by Tornhoof** [comment]
You're comparing string based enum serialization with integer based serialization. That's two different things.

**Comment by vitidev** [comment]
Ok. But integer based is more correctly. For example I receive json from remote api and deserialize to my structure. I can fix the mismatch of names with DataMember attribute, but based enum serialization require enum name equality. I have to write a converter with name translation

Also if api send integer value, I cannot deserialize it directly into enum. I need converter again.

Why such complexity with an unknown benefit from "string based enum serialization"

**Comment by Tornhoof** [comment]
Then use integer based enums. See the Main Page in how to do that, look for Custom Resolver.

**Comment by vitidev** [comment]
public sealed class CustomResolver<TSymbol> : ResolverBase<TSymbol, CustomResolver<TSymbol>> where TSymbol : struct
    {
        public CustomResolver() : base(new SpanJsonOptions
        {
            NullOption = NullOptions.ExcludeNulls,
            NamingConvention = NamingConventions.CamelCase,
            EnumOption = EnumOptions.Integer
        })
        {
        }
    }
    public class Item
    {
        public IntEnum IntEnum { get; set; }
        public StringEnum StringEnum { get; set; }
    }

    [Flags]
    public enum IntEnum
    {
        One = 1,
        Two = 2
    }

    public enum StringEnum
    {
        One,
        Two
    }

    class Program
    {
        static void Main(string[] args)
        {
            var json = "{\"IntEnum\":2,\"StringEnum\":\"Two\"}";
            var item = JsonSerializer.Generic.Utf16.Deserialize<Item, CustomResolver<char>>(json);
        }
    }
has result

    new Item
    {
        IntEnum = (SpanJsonTest.IntEnum)0,
        StringEnum = SpanJsonTest.StringEnum.One
    }

Where mistake?

In any case, I do not understand why not to translate the string values as an "string based", and numbers as "integer based" without additional resolvers.
And I can not check how they will be converted if the class contains both types of enums

**Comment by Tornhoof** [comment]
I think you misunderstand how enums work in c#. They always are integer based. Per Default SpanJson takes the enum name instead of the integer value for serialization. You can switch that to integers via a Custom Resolver.
It has nothing to do with Flags or if you define explicit integer values in your enum.

**Comment by vitidev** [comment]
That is no way to combine both options?
And cannot parse  

     {"IntEnum":1,"StringEnum":"Two"}

**Comment by Tornhoof** [comment]
No you can't use both options at the same time.

**Comment by vitidev** [comment]
I understand why. Concrete enum formatter resolve **once** there:

    if (type.IsEnum)
    {
        switch (_spanJsonOptions.EnumOption)
        {
            case EnumOptions.String:
            {
                if (type.GetCustomAttribute<FlagsAttribute>() != null)
                {
                    ...
                }
            }
            case EnumOptions.Integer: ...
        }
    }

and there is no way to distinguish "string enum" from "int enum" , since they are all is int

I do not really understand why "string enum format" was chosen as the default (for example System.Text.Json choose integer by default as "more efficient" and all enums are int by nature but I can always write a wrapper


    public T Deserialize<T>(string input)
    {
        return JsonSerializer.Generic.Utf16.Deserialize<Item, ExcludeNullCamelCaseIntegerEnumResolver<char>>(input);
    }
    

so I must create custom concrete CustomStringEnumFormatter and CustomIntEnumFormatter for override behavior, and use it with JsonCustomSerializerAttribute on enum property. Right?

If yes, **is it possible to add attributes like [StringEnum] and [IntEnum] with effective implementation, that will mix different enums in one json and not to write custom formatters every time?**

-------
but I still don't understand why this is not working

    public sealed class CustomResolver<TSymbol> : ResolverBase<TSymbol, CustomResolver<TSymbol>> where TSymbol : struct
    {
        public CustomResolver() : base(new SpanJsonOptions
        {
            NullOption = NullOptions.ExcludeNulls,
            NamingConvention = NamingConventions.CamelCase,
            EnumOption = EnumOptions.Integer
        })
        {
        }
    }
    public class Item
    {
        public IntEnum IntEnum { get; set; }
    }

    public enum IntEnum
    {
        One = 1,
        Two = 2
    }

    class Program
    {
        static void Main(string[] args)
        {
            var json = "{\"IntEnum\":2}";
            var item = JsonSerializer.Generic.Utf16.Deserialize<Item, CustomResolver<char>>(json);
        }
    }
    
result for IntEnum is 0;

**Comment by Tornhoof** [comment]
The Default is String, because it makes more sense for an Exchange format, otherwise each consumer needs to agree and understand the same integer values. In some languages you don't have enums etc.
The corefx implementation uses int as Default because it is the default enum type in asp.net since afaik the beginning.

**Comment by Tornhoof** [comment]
Your example doesn't work because you Set Camel Case in your Resolver, but your json snippet is Not Camel Case
