### ISSUE TITLE
incomplete deserialization from [FromBody]

### ISSUE THREAD

**Issue by vitidev** [Tornhoof/SpanJson#135]
SpanJson.AspNetCore.Formatter.

action:

       [HttpPut("import")]
       public async Task<IActionResult> Import([FromBody] ImportViewModel vm, CancellationToken ct)

ImportViewModel

    public class ImportViewModel
    {
        public List<Account> Accounts { get; set; }
    }

json from body

     {"Accounts":[{"Id":0,"Username":"username","Password":"password",...}]}

but vm.Accounts is null (with Newtonsoft.Json all ok)

how debug this and find the cause of the problem?

**Comment by Tornhoof** [comment]
The exception message should be in the logs via the modelstate context, if there isn't anything useful in there, I'd probably use the asp.net core formatter sources for SpanJson, add them manually and start from there.

**Comment by vitidev** [comment]
it is unreal to debug spanjson, so I tried to isolate issue

json

    { "Inners": [   {   "Id": 1,  "Username": "username"  } ]    }

models

    public class InputJsonModel
    {
        public List<InnerModel> Inners { get; set; }
    }
    public class InnerModel
    {
        public long Id { get; set; }

        public string Username { get; set; }
    }

there Inners = null

    public class AspNetCoreDefaultResolver<TSymbol> : ResolverBase<TSymbol, AspNetCoreDefaultResolver<TSymbol>> where TSymbol : struct
    {
        public AspNetCoreDefaultResolver() : base(new SpanJsonOptions
        {
            NullOption = NullOptions.IncludeNulls,
            NamingConvention = NamingConventions.CamelCase,
            EnumOption = EnumOptions.Integer
        })
        {
        }
    }

    var model = JsonSerializer.NonGeneric.Utf16.Deserialize<AspNetCoreDefaultResolver<char>>(json.AsSpan(), typeof(InputJsonModel));

reason in flag `NamingConvention = NamingConventions.CamelCase`

      //works (defaut IncludeNullsOriginalCaseResolver)
      var model= JsonSerializer.Generic.Utf16.Deserialize<InputJsonModel>(json.AsSpan());
      //works
      var model = JsonSerializer.NonGeneric.Utf16.Deserialize<IncludeNullsOriginalCaseResolver<char>>(json.AsSpan(), typeof(InputJsonModel));

      //not works
      var model = JsonSerializer.NonGeneric.Utf16.Deserialize<IncludeNullsCamelCaseResolver<char>>(json.AsSpan(), typeof(InputJsonModel));

is CamelCase != UpperCamelCase ?

**Comment by Tornhoof** [comment]
Camel Case is lowerCamelCase. 
See https://github.com/Tornhoof/SpanJson/blob/e13893f45e0aabf2c67e5a1c2cf148f133f81bbb/SpanJson/Resolvers/ResolverBase.cs#L155-L160
