### ISSUE TITLE
SpanJson.JsonSerializer.NonGeneric.Utf8.SerializeToArrayPool Error

### ISSUE THREAD

**Issue by liyuan0420** [Tornhoof/SpanJson#142]
https://images.gitee.com/uploads/images/2020/0113/150902_f361edb6_5617908.png

**Comment by liyuan0420** [comment]
Operation is not valid due to the current state of the object.

**Comment by Tornhoof** [comment]
Hello,
your linked image does not work, please provide a valid stacktrace and appropriate objects to reproduce your issue.

**Comment by silkfire** [comment]
Here's a copy of OP's original image:

![image](https://user-images.githubusercontent.com/1554615/72244258-3374c280-35ee-11ea-8efa-6824235cbc43.png)
