### ISSUE TITLE
Resolver TSymbol type

### ISSUE THREAD

**Issue by silkfire** [Tornhoof/SpanJson#144]
What's the type of the generic argument in resolvers supposed to be? I've seen both `char` and `byte` used, what's the difference?

E.g. `IncludeNullsOriginalCaseResolver<byte>` vs `IncludeNullsOriginalCaseResolver<char>`.

**Comment by Tornhoof** [comment]
``char`` is for use with the utf16 code paths.
``byte`` is for use with the utf8 code paths.
Pretty much all formatter etc. implementations provide both.

**Comment by silkfire** [comment]
Okay, isn't it better if the library determines which type it needs automatically depending on implementation used, instead of having the user provide that themselves (could lead to mistakes of one accidentally provides the wrong type)?

**Comment by Tornhoof** [comment]
It is quite hard to provide the wrong type for the normally used API. Example:
https://github.com/Tornhoof/SpanJson/blob/f25c010b630420d9655f3b4f85366b209ab55d3f/SpanJson/JsonSerializer.Generics.cs#L330-L334.
There are certain exceptions, but most of the time it's not possible to mix them up.
