### ISSUE TITLE
Don't escape forward slashes

### ISSUE THREAD

**Issue by silkfire** [Tornhoof/SpanJson#145]
Would it be possible to add a resolver / option that doesn't escape forward slashes?

https://stackoverflow.com/questions/1580647/json-why-are-forward-slashes-escaped

Forward slashes are optional to escape and it'd be nice to have a setting to disable this behavior.

So that `{a: "a/b/c"}` is not serialized as `{"a":"a\/b\/c"}`.

**Comment by Tornhoof** [comment]
The escape logic is very deep inside the writers. I don't think it's possible to make that configurable via the current static config system.

**Comment by drony** [comment]
i hate this completely destroy readability.
