### ISSUE TITLE
System.Text.JsonDocument with JsonPath Extension. Is there a similar easy way to extract part of data with SpanJson?

### ISSUE THREAD

**Issue by netcorefan1** [Tornhoof/SpanJson#147]
Hello,
my existing code uses System.Text.Json and I am going to do the necessary modifications to completely replace it with SPJ.
I often need to extract specific part of the json data.

STJ provides the nice JsonDocument which, combined to one of the [jsonpath extensions](https://github.com/blushingpenguin/BlushingPenguin.JsonPath), it allows me to do everything in one line of code:
`var jsonObject = json.SelectToken("$['store']['book'][0]['title']");`
Then, I just call `Deserialize()` and I get my class populated with data. And I'm done!

Now, I can just leave the extraction job to STJ and call SpanJson for deserialization, but I don't like this.

What would be the best way to completely remove any dependency to STJ and let do everything to the much more performant SPJ while keeping at the same time the same simplicity?

Thanks

**Comment by Tornhoof** [comment]
No, there is no easy way to achieve this, if at all. A rather large part of Spanjson's Performance is due to not having a DOM model. If your STJ Code is working, I recommend keeping it that way and wait for .NET 5's Performance improvements.  If you need higher performance that much, you can take a look at simdjson and https://github.com/EgorBo/SimdJsonSharp but it's not easy to use.

**Comment by netcorefan1** [comment]
Thanks for your support.
I was aware of SimdJsonSharp, but I have never taken it into consideration. I get maximum 300Kb-1Mb at once and in rare cases the whole data received goes over 10-15 Mb. I suppose that in these cases, SDJ will be even slower.
In addition to that, seeing the library bindings not anymore updated to match the native library, was another reason to forget about it. I am wrong with these assumptions?

Let me see if I understood well...

I tried to play with the JsonReader and I was able to access part of the json by calling `ReadBeginArrayOrThrow()`, `ReadBeginObjectOrThrow()`, `ReadNextToken()`, `skipX()`, `skipXX()` etc. 
Once learned what does the navigator functions with trials and error, I believe that I should be able to find and read the target object by using the shorter road and then deserialize it through the deserializer.
Is there something wrong with this approach?
Under the hood the JsonDocument from STJ uses the jsonReader in the same manner.

Another alternative approach...
Supposing a sample json structured like this:
![sample](https://user-images.githubusercontent.com/63934725/91671528-d64f6200-eb27-11ea-8fbc-2e8d6b199eb6.jpg)
I could replicate the same road to reach the target data with:
```
root_class
{
    obj3[] property;
}

obj3_Class
{
   // obj3 not included
    obj5[] property;
}
obj5_Class
{
   // objects 5 not included
   obj6 property;
   obj7[] property;
}
obj6_Class { //data }
obj7_Class { //data }
```
Then, I call directly "`SpanJson.JsonSerializer.Generic.Utf8.DeserializeAsync<root_class>(stream);`"
What you think between this and the other approach?

Regarding STJ improvements, the tests we performed in my previous post were against the latest preview version 5 of the library and I saw no difference. If you try to downgrade to version 3.1 (the same version bundled with .Net Core) and retry again the tests, you should experience the same.

Thanks

**Comment by Tornhoof** [comment]
If you know that you need a nested object, you can obviously model the path to it as an object structure, just like in your example, this will be faster than any manual code via JsonReader. You can try the dynamic code functionality of SpanJson, but I expect this will be quite a bit slower.

**Comment by netcorefan1** [comment]
Sorry for my delay. Faster and easier, this is enough to go for this route. I have some questions about this, but I prefer to first try to do things myself and then open an issue if I really can't find a way .
Just one thing about JsonReader since I may need it for a reason or another. For dynamic you mean `ReadUtf8Dynamic()` method of the JsonReader, right? I tried it, but it only gives me the name of the property and an array of bytes. 
I don't understand what I can do with it.
It's something that give me the whole substructure as a byte array which I can pass to the deserializer for direct deserialization? Without it, I should manually read each member to the target class with ReadBoolean(), ReadDateTime(), ReadString() etc etc. I am right? How you would estimate the difference in speed between dynamic and nondynamic?

I would appreciate if you could link me some documentation. I didn't found anything and the methods themself don't have any comment.
Thanks

**Comment by Tornhoof** [comment]
No, for dynamic I mean something like this: https://github.com/Tornhoof/SpanJson/blob/f25c010b630420d9655f3b4f85366b209ab55d3f/SpanJson.Tests/DynamicTests.cs#L362-L374
I don't have any performance comparisons between dynamic and typed serialization, but I expect it to be atleast two times slower.

Fwiw, I highly recommend not using JsonReader anywhere, as written before, doing this correctly requires handling several edge cases and probably a lot more I've forgotten by now. The JsonReader is just for the serializer. If you need manual JsonReader logic, use System.Text.Json, that JsonReader is in general atleast as fast as the one in SpanJson.

**Comment by netcorefan1** [comment]
Thanks for your help! You saved me from mistakes that I would have surely done. 
Ok, first plan is direct deserialization by replicating the required structure which bring me to the target data.
Second plan, if the first fail (or any other use cases) is JsonReader from STJ. as you recommended. 

But given that the JsonReader of JsonSpan is fast like STJ JsonReader, wouldn't be the same if I directly use JsonDocument given that under the hood it uses its JsonReader anyway (probably a wrapper) ? Or I am wrong meaning that dealing with JsonReader alone is still much faster than JsonDocument? Supposed you confirm JsonDocument will perform in the same way, can I expect [the same for the JsonPath extension](https://github.com/blushingpenguin/BlushingPenguin.JsonPath) or this will slow down eveything? It's very convenient, but I can live without it, it's just a bit of more work for JsonReader or JsonDocument (in case you approve it).
Regarding dynamic object, being two times slower is enough for me to leave it out, at least until I see I can go far with the other approaches.
Thanks

**Comment by Tornhoof** [comment]
I don't have any good performance guesses or ideas about the overhead of JsonDocument and/or that path extension.

**Comment by netcorefan1** [comment]
I understand, this is something that have to benchmarked. 
At think point I think that we can close since you provided me with very good starting points on how to manage what I am trying to do. 
Many thanks for your help! I really appreciated!
