### ISSUE TITLE
Support C# 9.0 records

### ISSUE THREAD

**Issue by silkfire** [Tornhoof/SpanJson#148]
With the advent of .NET 5.0 and C# 9 we now have a new, immutable-on-demand, kind of class with additional special features called `record`. Would it be possible to add support for them (especially the type known as [positional record](https://www.thomasclaudiushuber.com/2020/09/01/c-9-0-records-work-with-immutable-data-classes/)) out-of-the-box?

Right now using them as if they were a normal class gives this exception:

![image](https://user-images.githubusercontent.com/1554615/99197861-56837c00-2795-11eb-973b-a43f39457cf1.png)

```
public record SampleModel(string Name, bool Age);

var sample = JsonSerializer.Generic.Utf8.Deserialize<SampleModel, ExcludeNullsCamelCaseResolver<byte>>(Encoding.UTF8.GetBytes(jsonString));
```

Positional records only have one public constructor:

`var sample = new SampleModel("Name", 100);`

**Comment by Tornhoof** [comment]
Yeah, I plan to add support for it in the next few days. I just haven't looked into records much yet.

**Comment by silkfire** [comment]
Appreciate it, thanks. Let me know if you need any help or just general guidance :)

**Comment by Tornhoof** [comment]
I expect it will be a Hack solution, like described in https://stackoverflow.com/questions/63097273/c-sharp-9-0-records-reflection-and-generic-constraints and related GitHub issues like https://github.com/dotnet/csharplang/issues/4121

**Comment by silkfire** [comment]
That could be a justifiable tradeoff considering how easy and rapid positional records are to work with.

**Comment by Tornhoof** [comment]
I published 3.1.0-rc1 to include the records stuff. It was a bit more complicated than expected, as records also support a mixed concept where not only those positional properties are used but additionally normal properties. SpanJson did not support that by now (as soon as you used the constructor attribute, it only used that and nothing else, other properties would be ignored). So I had to extend it for this functionality.

**Comment by silkfire** [comment]
Thank you very much, I'll try it out tonight if I have time. Yeah I've read that they might improve reflection support for records in #C10 but until then we just might have to do with hacks :)

**Comment by silkfire** [comment]
@Tornhoof Just wanted to give you a heads up that I had few hours to test out the latest release of the library the other day and it worked perfectly. Even the `[DataMember]` attributes worked with positional records, so mapping JSON tokens with a different name than its corresponding property on the recos is not an issue. Well done!

**Comment by Tornhoof** [comment]
Great to hear, thanks for the Heads-up
