### ISSUE TITLE
Add option to exclude empty collections/lists

### ISSUE THREAD

**Issue by DavidErben** [Tornhoof/SpanJson#154]
Hello,

first of all, thanks for this amazing project. The performance of this serializer is really good and it improves the throughput of my API a lot. I have a question regarding serialization of collections/lists. Right now there is an option to exclude null values, but would it also be possible to exclude empty collection/lists?

To elaborate ... I am reading objects from a database, the database models are reverse engineered with EF Core. By default, all collections are initialized with an empty HashSet. So if this object now gets serialized, the value is not null and instead an empty collection, therefore gets serialized into JSON.

Example generated entity:

``` public partial class AuthUser
{
	public AuthUser()
	{
		  AuthUserGroups = new HashSet<AuthUserGroups>();
	}

	[Key]
	[Column("id", TypeName = "int(11)")]
	public int Id { get; set; }

	[InverseProperty("User")]
	public virtual ICollection<AuthUserGroups> AuthUserGroups { get; set; }
}
```

Example result JSON:

```
[
    {
        "Id": 1,
        "AuthUserGroups": []
    }
]
```

In some classes I have a lot of these navigation properties, so the JSON becomes quite big (in my case instead of 900kB it was 2MB ... for a list with around 1,5k objects).

Is there a way to handle this via a custom resolver or formatter? For custom formatter it says the following in your code:

> Only register primitive types here, no arrays etc. this creates weird problems.

So obviously this is not recommended? Is there another way to do this or would it be possible for you to add a similar option like "ExcludeNulls" for collection/lists ("ExcludeEmptyLists")?

Thanks a lot for this project and your help!

**Comment by Tornhoof** [comment]
The supported classic method is to add a method ``ShouldSerializePropertyName`` to your entity and use that. 
example:
```csharp
public bool ShouldSerializeAuthUserGroups()
{
   return AuthUserGroups?.Count > 0;
}
```
see also:
https://github.com/Tornhoof/SpanJson/blob/master/SpanJson.Tests/OptionalSerialization.cs#L9-L23

**Comment by DavidErben** [comment]
Ah ok, I see! Thanks for the explanation, then I will do it this way!
