### ISSUE TITLE
Support for DataMember(IsRequired)

### ISSUE THREAD

**Issue by exp111** [Tornhoof/SpanJson#161]
Hi
I started using this library to serialize/deserialize messages and found a case where I needed optional properties.
`DataMember(IsRequired=true/false)` would be a perfect fit for that but it doesnt seem like SpanJson supports that.
Exclude/IncludeNull Resolvers would probably not be enough because classes can contain both required nullable fields and optional non nullable fields.
The best thing atm would probably be to write a custom resolver that checks for the attribute (which may also not work for deserialization?), but I feel like this would be a general improvement for the library

**Comment by Tornhoof** [comment]
What should ``[DataMember(IsRequired)]`` solve? It is designed to fail the serialization process if required properties are missing. This is out of scope of the library, there is no validation of the incoming data.
If you want to control which values are serialized, the pattern you're looking for is ``ShouldSerializeXXX``.
