### ISSUE TITLE
DateTimeParser doesn't handle some formats

### ISSUE THREAD

**Issue by Upitep** [Tornhoof/SpanJson#162]
https://github.com/Tornhoof/SpanJson/blob/22b5c91b87c33652e64528543ff161ff83851bbe/SpanJson/Helpers/DateTimeParser.Utf8.cs#L347-L352

For many apis, the DateTime is specified in a similar format: **"2022-04-13T21:47:46.027+0000"** Unfortunately, this format causes a parsing error. Could you complete your parser?

**Comment by Tornhoof** [comment]
You mean the the offset is missing a colon?
The implementation in SpanJson is following the original ``Utf8Parser`` implementation and that one disallows that, as the RFC3339/ISO8601 profile disallows it. Runtime even closed a bug related to that https://github.com/dotnet/runtime/issues/30883.
So my answer here is no.
