### ISSUE TITLE
The specified argument is outside the range of valid values

### ISSUE THREAD

**Issue by iainxt** [Tornhoof/SpanJson#163]
I very rarely get the following error. It appears to self-resolve making me suspect it is intermittent based on something outside of the document being written. But I am really not sure, any suggestions apprechiated.

{"level":0,"method":"System.ThrowHelper.ThrowArgumentOutOfRangeException","assembly":"System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","line":0}

SpanJson.JsonWriter`1.WriteUtf8ReadonlySpan","assembly":"SpanJson, Version=3.1.0.0, Culture=neutral, PublicKeyToken=12740fa6726bc6d3","line":0}

{"level":2,"method":"SpanJson.JsonWriter`1.WriteUtf8String","assembly":"SpanJson, Version=3.1.0.0, Culture=neutral, PublicKeyToken=12740fa6726bc6d3","line":0}

**Comment by iainxt** [comment]
One theory I have is when the string contains escaped content. In that case we will be writing out the following

WriteUtf8ReadonlySpan(value.Slice(from, index - from), 7);

However when we get a chunk of bytes on the output we are not checking the length > 0

var output = _bytes.Slice(pos, _bytes.Length - pos - extraBytes);

If we have less than 7 bytes left in _output then we will be passing in a negative number for length.

**Comment by iainxt** [comment]
Yep, the bug is in that code, here is a test. It fails on i = 123.

        [Fact]
        public void EscapeGrowBug()
        {
            for (var i = 0; i < 1000; i++)
            {
                var obj = new JsonObjectSmall { N = new string('"', i) };
                var result = JsonSerializer.Generic.Utf8.Serialize(obj);
            }
        }

**Comment by iainxt** [comment]
Using Math.Max with 0 fixes it

var output = _bytes.Slice(pos, Math.Max(0, _bytes.Length - pos - extraBytes));

**Comment by Tornhoof** [comment]
Thank you for your bug report with the failing test, I'll take a look later today and fix that.

**Comment by iainxt** [comment]
Thanks for your quick reply! I have had it happen 3 times in 6 months so it is a pretty rare case. Thanks for the library, we have large documents and newtonsoft does not cut it for us.

**Comment by Tornhoof** [comment]
The bugfix should be in Release 3.2.1 on Nuget.

**Comment by iainxt** [comment]
Thanks I'll update.

I'm a little worried there is still a bug in there, as the code assumes the buffer always has 1 spare byte, but the code is growing it by 6 and the comment says it might use 6. In that case it might write the 6 byte escaped content and there are 0 bytes left in the buffer. The next non escaped byte will hit the same error.

I'll see if I can get a failing test over the weekend.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Tornhoof** [comment]
> but the code is growing it by 6 
Yeah, I noticed that after the build too, but it shouldn't matter, grow will always at least grow to twice the size. As long as it hits grow, the buffer will be correct.

**Comment by iainxt** [comment]
My concern is when there are exactly 6 bytes left, it won't grow and will leave 0 bytes. The growing by 2x does make this edge case even less likely than the last

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Tornhoof** [comment]
Ah okay, you mean if it does not grow. Good question, I'll do another release to change the comparison and grow value to 7.

**Comment by Tornhoof** [comment]
3.2.2 includes the changed grow size
https://www.nuget.org/packages/SpanJson/3.2.2

**Comment by iainxt** [comment]
Thanks I'll take a look

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
