### ISSUE TITLE
How should I define the class of this serialized string?

### ISSUE THREAD

**Issue by libu1129** [Tornhoof/SpanJson#167]
============================================================
{
  "e": "depthUpdate", // Event type
  "E": 123456789,     // Event time
  "T": 123456788,     // Transaction time 
  "s": "BTCUSDT",     // Symbol
  "U": 157,           // First update ID in event
  "u": 160,           // Final update ID in event
  "pu": 149,          // Final update Id in last stream(ie `u` in last stream)
  "b": [              // Bids to be updated
    [
      "0.0024",       // Price level to be updated
      "10"            // Quantity
    ]
  ],
  "a": [              // Asks to be updated
    [
      "0.0026",       // Price level to be updated
      "100"          // Quantity
    ]
  ]
}

===========================================================

public class item_vm {
    public string[][] b { get; set; } //bid
    public string[][] a { get; set; } //ask
}

is not working
I don't know what to declare the data structure for 2darray

**Comment by libu1129** [comment]
{
   "e":"depthUpdate",
   "E":1655482017143,
   "T":1655482017133,
   "s":"BTCUSDT",
   "U":1625325681622,
   "u":1625325684678,
   "pu":1625325681451,
   "b":[
      [
         "20663.10",
         "1.201"
      ],
      [
         "20663.00",
         "0.001"
      ],
      [
         "20662.80",
         "0.001"
      ],
      [
         "20662.40",
         "0.154"
      ],
      [
         "20662.30",
         "0.099"
      ],
      [
         "20662.10",
         "0.018"
      ],
      [
         "20661.90",
         "0.001"
      ],
      [
         "20661.60",
         "0.196"
      ],
      [
         "20661.50",
         "1.218"
      ],
      [
         "20661.30",
         "0.001"
      ],
      [
         "20661.20",
         "0.095"
      ],
      [
         "20661.10",
         "0.126"
      ],
      [
         "20661.00",
         "0.224"
      ],
      [
         "20660.90",
         "0.025"
      ],
      [
         "20660.70",
         "0.290"
      ],
      [
         "20660.60",
         "0.050"
      ],
      [
         "20660.50",
         "1.400"
      ],
      [
         "20660.40",
         "0.239"
      ],
      [
         "20660.30",
         "3.774"
      ],
      [
         "20660.10",
         "0.700"
      ]
   ],
   "a":[
      [
         "20663.20",
         "0.423"
      ],
      [
         "20663.70",
         "0.001"
      ],
      [
         "20664.70",
         "0.043"
      ],
      [
         "20664.80",
         "0.835"
      ],
      [
         "20665.10",
         "0.711"
      ],
      [
         "20665.30",
         "0.031"
      ],
      [
         "20665.40",
         "0.001"
      ],
      [
         "20665.60",
         "0.290"
      ],
      [
         "20665.80",
         "0.054"
      ],
      [
         "20666.20",
         "0.006"
      ],
      [
         "20666.30",
         "0.019"
      ],
      [
         "20666.60",
         "0.699"
      ],
      [
         "20666.70",
         "1.774"
      ],
      [
         "20666.80",
         "0.290"
      ],
      [
         "20666.90",
         "0.337"
      ],
      [
         "20667.20",
         "0.701"
      ],
      [
         "20667.30",
         "4.313"
      ],
      [
         "20667.40",
         "0.436"
      ],
      [
         "20668.20",
         "0.489"
      ],
      [
         "20668.30",
         "0.005"
      ]
   ]
}




        public class tmp1 {
            [DataMember(Name = "e")]
            public string e { get; set; }
            [DataMember(Name = "E")]
            public long E { get; set; }
            public long T { get; set; }
            public string s { get; set; }
            [DataMember(Name = "U")]
            public long U { get; set; }
            [DataMember(Name = "u")]
            public long u { get; set; }
            public long pu { get; set; }

            public string[][] b { get; set; } //bid
            public string[][] a { get; set; } //ask
        }


SpanJson.JsonSerializer.Generic.Utf16.Deserialize<tmp1>(str);

=============================================================


Sorry, the question is invalid.  :(
This seems to be a problem other than deserializing the array.
Attached is an example that can be reproduced.

The following exception occurs:


The type initializer for 'Inner`3' threw an exception


I don't know why this problem is happening

**Comment by Tornhoof** [comment]
you misunderstood my comment:
> them uniquely enough and then assign the field names via [DataMember(Name = "U")]. members which only differ in casing is not well supported or tested.

Do not name the members just with different casing. Call them e.g. "e1" and "E2", don't call them "e" and "E".  The exception you get, if you'd list them properly, is an AmbiguousMatchException which means that you have properties which only differ in casing.

**Comment by libu1129** [comment]
Thank you for your kind explanation.
The problem has been resolved.
