### ISSUE TITLE
Error when deserializing Array of objects with constructor in object

### ISSUE THREAD

**Issue by antomys** [Tornhoof/SpanJson#172]
# Hello! I am facing issues with deserializing array of object models using Span.Json 

## Here attaching stacktrace below:

```
SpanJson.JsonParserException: Error Reading JSON data: 'ExpectedSeparator' at position: '1'.
   at SpanJson.JsonReader`1.ThrowJsonParserException(ParserError error)
   at SpanJson.Formatters.ArrayFormatter`3.Deserialize(JsonReader`1& reader)
   at SpanJson.JsonSerializer.Generic.Utf16.Deserialize[T,TResolver](String input)
   at SpanJson.JsonSerializer.Generic.Utf16.Deserialize[T](String input)
   at Program.<Main>$(String[] args) in /Users/ihor.volokhovych/RiderProjects/SpanJson.DeserializationErrorExample/SpanJson.DeserializationErrorExample/Program.cs:line 23
```
## https://github.com/antomys/SpanJson.DeserializationErrorExample

I have figured out, that it is because model has constructor with values, empty but no setters or initters. To reproduce simply create any object

```
public sealed class TestErrorModel
{
    public TestErrorModel()
    {
    }
    public TestErrorModel(int intNumber, string stringValue)
    {
        IntNumber = intNumber;
        StringValue = stringValue;
    }
    public int IntNumber { get; }
   
    public string StringValue { get; }
}
```

Make an array of values and try to deserialize with any UTF8 deserializer from SpanJson

Error is while executing
`while (!reader.TryReadIsEndArrayOrValueSeparator(ref count)) // count is already preincremented, as it counts the separators`
in file `SpanJson.Formatters.ArrayFormatter` on line 34.

It throws exception right here in `JsonReader` (line 93)
![Screenshot 2022-07-29 at 00 32 50](https://user-images.githubusercontent.com/50595040/181641368-35032b2c-3dc7-4784-8c0b-b646bb33a7d1.png)

**Comment by antomys** [comment]
@Reris Probably would be interesting for you too

**Comment by Tornhoof** [comment]
Why do you think this is an error?
you have two ctors, you need to annotate one with with ``[JsonConstructor]``.

**Comment by antomys** [comment]
Damn. Thanks, @Tornhoof. It slipped my mind that i have to place an attribute above ctor. Thanks, you saved hundreds of hours
