### ISSUE TITLE
is it possible to create a custom formatter for a type that is not editable?

### ISSUE THREAD

**Issue by benthemos** [Tornhoof/SpanJson#173]
would like to write custom formatters for some google protocol buffer types

**Comment by Tornhoof** [comment]
What do you mean with not editable?
You mean no setters?
You could just implement the serialization side.

**Comment by benthemos** [comment]
I mean a type that is in another assembly that I cannot edit

**Comment by benthemos** [comment]
I have dtos in auto-generated assemblies that contain google protobuf Timestamp properties, and I'd like to write a custom formatter for Timestamp as the default serialisation is not human readable

**Comment by Tornhoof** [comment]
There is a concept for GlobalCustomFormatters
https://github.com/Tornhoof/SpanJson/blob/master/SpanJson.Tests/GlobalCustomFormatter.cs

But it's quite involved to get it working properly, that might work. Other than that? Probably not.

**Comment by benthemos** [comment]
looks perfect, thanks, I'll have a go
