### ISSUE TITLE
SpanJsonDynamicObject unclear with NamingConvention

### ISSUE THREAD

**Issue by Reris** [Tornhoof/SpanJson#175]
Well not THAT important, but a minor issue in namings:

Using dynamic in SpanJson is a bit tricky: While Serialize() uses the defined naming convention, Deserialize() doesn't.

```
dynamic x = /// new;
x.Name = "Foo";
var json = JsonSerializer.NonGeneric.Utf16.Serialize<CamelCaseResolver<char>>(x);
dynamic y = JsonSerializer.NonGeneric.Utf16.Deserialize<CamelCaseResolver<char>>(json, typeof(object));
// y.name == "Foo"
// y.Name == Error
```

From a Json-Perspective: this is ok. But from a programmer perspective (I think) this is a breach of the convention.
What's your opinion - keep as-is - or - change SpanJsonDynamicObject to use PascalCasing when the serialization was in CamelCasing - or - new SpanJsonOptions property?

**Comment by Tornhoof** [comment]
Oh god, dynamic. If I remember correctly, the idea here was, and it should be asserted by a few tests, is that if you can't build a proper dto for your types, the dynamic deserialization outputs the property name as written in the json.

The proper approach is probably to rip out the whole dynamic abomination ;)

I understand you concerns, but I highly recommend leaving it as is,

**Comment by Reris** [comment]
:D
I use it only in a veeery special scenario too: Automatic testing with a big amount of sequential data stored in a file, where the file structure is '[{ "url": "#stringSendToAdress", "data": {#dynamicData} }, ...].
This allows me to deserialize and send data with varying models.

So yeah... there actually is a use case - but at least for me, it's fine to keep it as-is. :)
/close
