### ISSUE TITLE
Nested object/values returns Error Reading JSON data: 'ExpectedSeparator' at position: '126'.

### ISSUE THREAD

**Issue by ajvwray** [Tornhoof/SpanJson#178]
I'm getting an odd deserializer error part way through this: 

> {"Collection":{"0de477fe-19ae-4e36-923f-d62a838377e2":{"PartitionKey":"f301e08a-074c-4c33-8b0c-0e65f2675b0a","PrimaryKey":{"PartitionKey":"f301e08a-074c-4c33-8b0c-0e65f2675b0a","EntityKey":"0de477fe-19ae-4e36-923f-d62a838377e2"},"State":{"RiskLevels":[],"IsDirty":false}}}}

I cant work out why but because its a nested object its just not happy!

**Comment by Tornhoof** [comment]
Can you provide the dto this should be deserialized into?

**Comment by ajvwray** [comment]
> Can you provide the dto this should be deserialized into?

Its not specifically complicated but it does use generics so harder to share 

Its a simple class with a concurrent dictionary 

`public class IndexerState<TState>`
`{`
`    public ConcurrentDictionary<Guid, IndexCollection<TState>> Collection { get; set; } = new();`
`}`


TState is just 

`public partial class RiskState`
`{`
`    public RiskDto Risk { get; set; }`
``
    public string AccountStatus { get; set; }
``
`    public List<RiskLevelDto> RiskLevels { get; } = new();`
`}`


and RiskDto 


`public class RiskDto`
`{`
`    public string RiskName { get; set; }`
`}`


and RiskLevelDto


`public class RiskLevelDto`
`{`
`    public int Level { get; set; }`
`    public string Name { get; set; } = default!;`
`    public string Description { get; set; } = default!;`
`    public bool Disabled { get; set; }`
`}`

**Comment by Tornhoof** [comment]
And what is IndexCollection<TState>> supposed to be?

**Comment by ajvwray** [comment]
> And what is IndexCollection> supposed to be?

Just getting to that! 

`public struct IndexCollection<TState> `
`    {`
`        public Guid PartitionKey => PrimaryKey.PartitionKey;`
`        public PrimaryKey PrimaryKey { get; set; }`
`       public TState State { get; set; }`

Primary Key is another struct which is just 2 guids but is readonly

**Comment by Tornhoof** [comment]
And please take a look at the readme:
```ini
Dictionary, ConcurrentDictionary with string/int/enum as key, the enum is formatted as a string
```

There is no support for Guids as keys in dictionaries.
