### ISSUE TITLE
parse case-sensitive json data (when Data and data both present)

### ISSUE THREAD

**Issue by traderqq** [Tornhoof/SpanJson#180]
By default it seems to be ignoring the case, 
so I tried  with custom resolver like that:
`var deserialized = JsonSerializer.Generic.Utf8.Deserialize<my_class, ExcludeNullsOriginalCaseResolver<byte>>(byte_data);`

and it still crashes with AmbiguousMatchException: Ambiguous match found.

I read all the docs and browsed source code, but could not figure out how to do this.

**Comment by Tornhoof** [comment]
If the same property with both casings exists, the behavior is not defined and thus not supported.

**Comment by Tornhoof** [comment]
If you search for issues with AmbiguousMatchException, you'd find
https://github.com/Tornhoof/SpanJson/issues/167#issuecomment-1159046081
That describes a workaround for your problem.
