### ISSUE TITLE
how to deserialize object from jsonreader

### ISSUE THREAD

**Issue by srxqds** [Tornhoof/SpanJson#183]
is there any method can  deserialize object from jsonreader, like below:
```c#
public T Deserialize(ref JsonReader<byte> reader)
{
    // like this implemented
    return reader.Deserialize<T>();
}
```

**Comment by Tornhoof** [comment]
Directly?
No.
If you know the Type, you can go can call the formatters directly, like in the examples for the CustomFornatters:
https://github.com/Tornhoof/SpanJson/blob/master/SpanJson.Tests/CustomSerializerTests.cs

If you know the actual Resolver you're using, you can do it like this:
```csharp
var formatter = StandardResolvers.GetResolver<byte, ExcludeNullsOriginalCaseResolver<byte>>().GetFormatter<T>()                return formatter.Deserialize(ref reader);
```
That's basically the core of the Deserializer static method, see: https://github.com/Tornhoof/SpanJson/blob/88a4b08a6e14305e2a60f7fdd42f2febd18db3e2/SpanJson/JsonSerializer.Generics.cs#L151-L155

But that helps only if you build your own Formatters, not even for CustomFormatters really.

**Comment by srxqds** [comment]
and another quesion how can i deserialize object with type from JsonReader<TSybmol>
```
public object Deserialize(ref JsonReader<byte> reader, Type type)
{
    // like this implemented
    return reader.Deserialize(type);
}
```
