### ISSUE TITLE
does SpanJson have ·ReadNextBlockSegment·  implemented？

### ISSUE THREAD

**Issue by srxqds** [Tornhoof/SpanJson#184]
is there any method like ReadNextBlockSegment in utf8json?

**Comment by Tornhoof** [comment]
How should I know what that method does?
 If you mean a method which reads and returns the data for the next element as a byte array, then the answer is no, SpanJson does not make the internal buffer available to the user in an API.

**Comment by srxqds** [comment]
> If you mean a method which reads and returns the data for the next element as a byte array
yes, we want custom deserialize type from un sorted property name, our case is :
the class has two fields A and B, Adeserialize depend on B, if we read first A, we should read util B so we can deserialize it.

**Comment by srxqds** [comment]
you can find the implemented at https://github.com/neuecc/Utf8Json/blob/608cf01589cb3feb225a6e51a2324a24466fdaa6/src/Utf8Json/JsonReader.cs#L1031

**Comment by srxqds** [comment]
I have opened pr: https://github.com/Tornhoof/SpanJson/pull/185
