### ISSUE TITLE
Return written bytes count for async method calls

### ISSUE THREAD

**Issue by lastdan** [Tornhoof/SpanJson#187]
I use async method to write data directly into an output stream of HttpListenerResponse. But I also need to set Content-Length header. Is it possible to return the number of bytes written? Or maybe it's not an appropriate way of using this kind of methods?

**Comment by Tornhoof** [comment]
Depending on how the internal serializers work, the exact byte count written to the stream is an implementation detail. I'd recommend wrapping your outputstream in a wrapper stream recording the written byte count and using that. 
Or use the sync API serializing to the Arraypool ``SerializeToArrayPool(input)`` and take the length from there (do not forget to return the array to the pool), that's basically what the async method does.
