### ISSUE TITLE
Support JsonExtensionData on IEnumerable<KeyValuePair<string, object>>

### ISSUE THREAD

**Issue by ulbodk** [Tornhoof/SpanJson#189]
Hi,

The "dynamic" serialization of `IDictionary<string, object>` works nicely but it does force caller to allocate a new dictionary even in cases where the dynamic nodes are only present as an `IEnumerable<KeyValuePair<string, object>>`.

Can this be changed to also support dynamic json from `IEnumerable<KeyValuePair<string, object>>`?

**Comment by Tornhoof** [comment]
You're using [JsonExtensionData] for serialization. But why?
As soon as you use extension data, you're already in the runtime serialization code, as it needs to decide at runtime what the type of the value is. This is not efficient anymore. Having an extra allocation for the dictionary will not make much difference there.

JsonExtensionData is designed for deserialization, where suddenly unknown keys show up and you don't want to lose them.

Spanjson is designed to work on fully typed models, everything else works suboptimal at best.

**Comment by ulbodk** [comment]
Makes sense, thanks!
