### ISSUE TITLE
Can't deserialize from json to class inheriting another class

### ISSUE THREAD

**Issue by Aangbaeck** [Tornhoof/SpanJson#190]
I get an error when I try to deserialize from json to a simple POCO-class inheriting properties from a base class (that I would like to populate as well). 

```SpanJson.JsonParserException: 'Error Reading JSON data: 'ExpectedDoubleQuote' at position: '45'.```

Is there a way around this? Newtonsoft handles it well but I would like the speed of SpanJson.

**Comment by Tornhoof** [comment]
Please provide steps to reproduce your Problem.

**Comment by Aangbaeck** [comment]
Ok, it seem to be able to handle polymorphism. I found the issue though.
It's the difference in the formatting of the json. 

myJson:
"{\"IsStocked\":false,\"PARTNO\":\"0\",\"COMPNO\":33}"

spanJSON: 
"{\"IsStocked\":\"false\",\"PARTNO\":\"0\",\"COMPNO\":33}"

Seems like booleans have double quotes "true" instead of the ordinary true.

**Comment by Tornhoof** [comment]
Then the type of your IsStocked is not bool

**Comment by Aangbaeck** [comment]
Ahh, of course... I will find my way out myself... :D Thanks!!
