### ISSUE TITLE
Add support to DateOnly and TimeOnly

### ISSUE THREAD

**Issue by josago97** [Tornhoof/SpanJson#192]
Would it be possible to add support for DateOnly and TimeOnly types? Both were added in .NET 6.

Thank you.

**Comment by OlsonDev** [comment]
@Tornhoof I'm attempting to implement this, however I have a question about some of the code in `JsonSharedConstant`:
```csharp
public const int MaxVersionLength = 45; // 4 * int + 3 . + 2 double quote
public const int MaxDateTimeOffsetLength = 35; // o + 2 double quotes
public const int MaxDateTimeLength = 35; // o + 2 double quotes
public const int MaxTimeSpanLength = 27; // c + 2 double quotes
public const int MaxGuidLength = 42; // d + 2 double quotes
```

Using LINQPad, I've constructed what I think would be the max length of each of these:
![image](https://github.com/Tornhoof/SpanJson/assets/308072/2a0cf212-df54-49f5-bf16-395d69baa282)

Note that I ran this a handful of times assuming the fractional seconds could potentially be truncated, but I saw trailing zeroes, so it appears that's not the case.

- `Version`: 43 + 2 = 45; math checks out
- `DateTimeOffset`: 33 + 2 = 35; math checks out
- `DateTime`: 33 + 2 = 35; math checks out
- `TimeSpan`: 16 + 2 = 18; math DOESN'T check out
- `Guid`: 36 + 2 = 38; math DOESN'T check out

Am I missing something or is this a bug I stumbled upon?

Thanks!

**Comment by OlsonDev** [comment]
Realized my error on `TimeSpan` -- ignore that. Still confused about the `Guid` one though.

**Comment by Tornhoof** [comment]
You're right about Timespan, I probably did not use MinValue, but MaxValue.

Can't remember why Guid is 42.

**Comment by OlsonDev** [comment]
Looking at `Utf8Parser.TryParse` for `Guid`, it appears they support these formats:

![image](https://github.com/Tornhoof/SpanJson/assets/308072/97a7989f-918a-4e43-84b9-b75dec64f450)

Whereas `Guid.ToString()` has these format specifiers, including the awkward `"X"` format (which would be a length of `68` + `2`):

![image](https://github.com/Tornhoof/SpanJson/assets/308072/eb5ca4e5-d5aa-474d-bf24-7a9900b648dd)

Since you're using `Utf8Parser.TryParse` under the hood, unless you disagree, I think I'll update that one to `40` to match the `"B"` and `"P"` max lengths.

**Comment by Tornhoof** [comment]
All the custom formatting is useless by now, it should simply call the methods from ``ISpanFormattable`` or ``IUtf8SpanFormattable`` by now.
The runtime formatting methods should be a lot faster than my own ones by now.

**Comment by OlsonDev** [comment]
That makes sense for writing, but what about reading?

**Comment by Tornhoof** [comment]
Same thing ``IUtf8SpanParsable`` and ``ISpanParsable``. I think utf-8 was added for . NET 8

**Comment by Tornhoof** [comment]
Looks Like MS punted the ``IUtf8SpanParsable`` for the interesting types like ``DateTimeOffset`` to the future

**Comment by OlsonDev** [comment]
Got it. Yeah, I was also seeing that `DateOnly` and `TimeOnly` don't implement `IUtf8SpanParsable<T>`, even in their `release/9.0-preview6` branch.

I'm not positive that theirs would outperform yours in that there's a lot of branching, specific error messages, style checking, no aggressive inlining, allocating a date-time amount of bytes for a date-only or time-only amount of data (probably on the stack, so likely to not actually matter, but it's also going through a ctor that initializes a bunch of fields to `-1` after they've likely already been initialized to `0` whereas your methods check each index.

What do you think? ... to be honest, I had already implemented much of this following your conventions, adding a few optimizations to your stuff along the way, but unfortunately had multiple terminals open and accidentally `git checkout .` in the wrong one. 🤦🏻‍♂️ Either way, it's still fresh in my mind, so I could do it that way. But if your long-term vision is to just use their BCL stuff, I won't bother.

**Comment by OlsonDev** [comment]
Oh, I was also going to say that you have code that checks that a certain amount of bytes/chars were read to validate everything up to the `"` was valid, whereas these new interfaces don't return anything like that. Probably edge case, but I did think that was a useful validation so you could for instance support `TimeOnly`s like:
- `"23:59"`
- `"23:59:59"`
- `"23:59:59.9"`
- - `"23:59:59.9999999"`

**Comment by Tornhoof** [comment]
Feel free to do it the current way.

There is no long time vision, it might change with the improved ROS and ref struct support in .NET9, but I doubt it. I don't use SpanJson anymore, the only interesting thing would be proper async support via srcgen, but async  with ref struct s won't bei easier in .NET 9 either.

**Comment by OlsonDev** [comment]
What's ROS?

**Comment by Tornhoof** [comment]
``ReadOnlySpan``. The idea apparently is to make Span/ROS a first class citizen in .NET 9. 
See 
https://github.com/dotnet/csharplang/blob/main/proposals/first-class-span-types.md

**Comment by Tornhoof** [comment]
@OlsonDev  just wondering, do you use Visual Studio for Dev or something else?
The changed t4 templates don't work in Visual Studio, as .NET Framework 4.8 does not have DateOnly/TimeOnly, I'll write a polyfill for the t4 templates for that.

**Comment by OlsonDev** [comment]
I use VS Code. I have [these](https://marketplace.visualstudio.com/items?itemName=zbecknell.t4-support) two [extensions](https://marketplace.visualstudio.com/items?itemName=jacknq.TextTemplating) installed -- I don't remember if I used one or the other, or neither, though. 😅

I'm not sure how the proper `TextTransform.exe` is getting called for me. If you want, I can dig into it. All the tests are passing for .NET 8 for me, but it appears they're not running at all for .NET 6. I can dig into that.

Looks like the .NET 6 ones passed on the [PR build](https://dev.azure.com/tornhoof/SpanJson/_build/results?buildId=88&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=59a85588-b0ba-5043-24c4-d9e29d89c6f6&l=32) though. So, just a matter of my local having something misconfigured.

**Comment by Tornhoof** [comment]
Ah okay, VS Code might behave differently there.

**Comment by Tornhoof** [comment]
4.2.0 will contain your changes. Thank you again.
