### ISSUE TITLE
Enum Converter

### ISSUE THREAD

**Issue by antomys** [Tornhoof/SpanJson#196]
Hello!  I am wondering, is there any possibility to specifically define enum handling strategy for each enum property in class like it's done in System.Text.Json?

For example, they have attribute [JsonConverter], where we can define strategy of handling this specific property

```
[JsonConverter(typeof(JsonStringEnumConverter))]
public MyEnum MyEnumProperty { get; init; }
```

Firstly, i thought that

```
[JsonCustomSerializer(typeof(EnumStringFormatter<,,>))]
public MyEnum MyEnumProperty { get; init; }
```

should work just fine, but according to the documentation and the eimplementation of a formatter, this is impossible.

So, is there any possibility now to declare specific handler of Enum to a specific enum property?

Global enum handling strategy is cool, but in my case i can have one Enum as value, but another as name. And having attribute can significantly help in that hell. Thanks for the response.

**Comment by Tornhoof** [comment]
Yeah you can, you need to have a proper CustomFormatter for it, see https://github.com/Tornhoof/SpanJson/blob/master/SpanJson.Tests/CustomSerializerTests.cs for an example
