### ISSUE TITLE
Support for EmitDefaultValue in DataMember?

### ISSUE THREAD

**Issue by vadim-berman** [Tornhoof/SpanJson#204]
Request: support `EmitDefaultValue`. Those using `DataMember` rely on it to suppress junk boilerplate JSON. 

Alternatively, please point out to custom classes that can be used to bypass these properties.

**Comment by Tornhoof** [comment]
You can use the ShouldSerializeXXX pattern to decide if you want to serialize a value. 
See https://github.com/Tornhoof/SpanJson/blob/3849bc28847e2e3ec6d2474283f512a3315b42ae/SpanJson.Tests/OptionalSerialization.cs for an example

**Comment by vadim-berman** [comment]
Great, thank you, @Tornhoof!
