### ISSUE TITLE
Force converting Unicode characters to escape sequences

### ISSUE THREAD

**Issue by vadim-berman** [Tornhoof/SpanJson#209]
Hello,

In our C++ library, we're having issues decoding some emoji. Is it possible to force SpanJson store Unicode strings as escape sequences? E.g. `🐀` -> `\ud83d\udc00`.

**Comment by Tornhoof** [comment]
No. There is no way to control the encoding of different characters. You'd need to go the füll route and write it yourself via custom formatters.

See e.g. #145
