### ISSUE TITLE
Using JsonPropertyName

### ISSUE THREAD

**Issue by GabrielMarquezMatte** [Tornhoof/SpanJson#212]
Good afternoon. I was wondering if there is a reason to have DataMemberAttribute as preference for property naming instead of the JsonPropertyNameAttribute. Also if the support for the JsonPropertyNameAttribute can be implemented for the package

**Comment by Tornhoof** [comment]
Spanjson predates System.Text.Json by a few years. There are no plans to implement support for that Attribute.

**Comment by GabrielMarquezMatte** [comment]
So I guess that me implementing a solution for this issue is out of the question, right?

**Comment by Tornhoof** [comment]
Yes, I'm sorry.
