### ISSUE TITLE
Bug: UTF16 JSON decoding does not handle number exponents in the same way as the UTF8 path

### ISSUE THREAD

**Issue by v3xro** [Tornhoof/SpanJson#216]
Found this while testing with WebsocketClient library (which already gives string rather than raw byte[] output):

See https://dotnetfiddle.net/u1Zua5 or below:

```c#
using System;
using SpanJson;
using System.Text;

record Foo(decimal Bar);
					
public class Program
{
	public static void Main()
	{
		var json = """{"Bar":9.2101e-6}"""u8.ToArray();
		var jsonS = Encoding.UTF8.GetString(json);
		
		Console.WriteLine("UTF8:");
		Console.WriteLine($"{JsonSerializer.Generic.Utf8.Deserialize<Foo>(json)}");
		Console.WriteLine("UTF16:");
		Console.WriteLine($"{JsonSerializer.Generic.Utf16.Deserialize<Foo>(jsonS)}");
	}
}
```

The output should be identical but the second example currently throws:

```System.FormatException: The input string '9.2101e-6' was not in a correct format.```

.NET 8, SpanJson 4.2.0

**Comment by Tornhoof** [comment]
Indeed , it looks like the uft16 path is missing the flag for exponential symbols

**Comment by v3xro** [comment]
Ah this is because on the utf8 path it's handled using `Utf8Parser.TryParse` and on the string path with `Decimal.TryParse` where an additional `NumberStyles.AllowExponent` flag would be needed?

**Comment by Tornhoof** [comment]
Yup, that's my guess from the flags.

**Comment by v3xro** [comment]
Yeah it is - if you look at the source of that Utf8Parser method: https://github.com/dotnet/runtime/blob/5535e31a712343a63f5d7d796cd874e563e5ac14/src/libraries/System.Private.CoreLib/src/System/Buffers/Text/Utf8Parser/Utf8Parser.Decimal.cs#L38C21-L74C25
