### ISSUE TITLE
Support for tuples (as json arrays)

### ISSUE THREAD

**Issue by v3xro** [Tornhoof/SpanJson#218]
I was not able to find a test that exercises a concrete Tuple<...> path but it is quite common to see a fixed-length array in JSON documents that represents a tuple of values.

Example:

```csharp
using System;
using SpanJson;

public sealed record TestOne((decimal, decimal, int)[] Stuff);

var json = """{"Stuff":[[1,2,3],[4,5,6]]}"""u8.ToArray();

Console.WriteLine(JsonSerializer.Generic.Utf8.Deserialize<TestOne>(json));
```

Currently (4.2.1, .NET 8) - the error thrown is `Error Reading JSON data: 'ExpectedBeginObject' at position`

Please feel free to close if there's an alternative way to support this.

**Comment by Tornhoof** [comment]
The value tuple you have needs to be modelled as an object. And even then value tuples are not well supported.
