### ISSUE TITLE
can provider TextWriter of utf8 serializer?

### ISSUE THREAD

**Issue by luohuazhiyu** [Tornhoof/SpanJson#24]
asp.net core integration need the interface: SerializeAsync(object input, TextWriter writer, CancellationToken cancellationToken = default(CancellationToken))

**Comment by Tornhoof** [comment]
There is
``` csharp
ValueTask result = JsonSerializer.Generic.Utf16.SerializeAsync(input, textWriter, cancellationToken);
ValueTask result = JsonSerializer.NonGeneric.Utf16.SerializeAsync(input, textWriter, cancellationToken);
```
which are the right methods for UTF16 serialization into a TextWriter.

If you want to serialize UTF8, you serialize into streams, you don't use the texwriter/reader:
```csharp
ValueTask result = JsonSerializer.Generic.Utf8.SerializeAsync(input, stream, cancellationToken);
ValueTask result = JsonSerializer.NonGeneric.Utf8.SerializeAsync(input, stream, cancellationToken);
```

If you're writing an OutputFormatter for ASP.NET Core, you're most likely using the wrong code,
take a look at:
https://github.com/Tornhoof/SpanJson/blob/master/SpanJson.WebBenchmark/Infrastructure/SpanJsonOutputFormatter.cs

and for InputFormatter
https://github.com/Tornhoof/SpanJson/blob/master/SpanJson.WebBenchmark/Infrastructure/SpanJsonInputFormatter.cs

You don't use ``context.WriterFactory`` for utf8.

**Comment by luohuazhiyu** [comment]
thank you

**Comment by luohuazhiyu** [comment]
@Tornhoof thank you
