### ISSUE TITLE
How to serialize Enum to Int32?

### ISSUE THREAD

**Issue by luohuazhiyu** [Tornhoof/SpanJson#30]
The default Enum serialization is String, but I want to serialize it to Int32.

**Comment by Tornhoof** [comment]
The short way is to use 
``JsonCustomSerializer`` at the moment and implement a formatter for it.
But that does mean applying it to each enum property. 

There currently is no way to do it globally.
I'll put it on the To-Do list.

**Comment by Tornhoof** [comment]
I wrote a custom formatter for integer, but using it is a bit uncommon.
Because all options are actually concrete classes, you need to create your custom formatter resolver class, like this:
```csharp
public sealed class CustomResolver<TSymbol> : ResolverBase<TSymbol, CustomResolver<TSymbol>> where TSymbol : struct
{
    public CustomResolver() : base(new SpanJsonOptions
    {
        NullOption = NullOptions.ExcludeNulls,
        NamingConvention = NamingConventions.CamelCase,
        EnumOption = EnumOptions.Integer
    })
    {
    }
}
```

and pass that one to the serializer, just like with ``ExcludeNullsOriginalCase<byte>``.

This is currently necessary, otherwise the amount of different resolver classes rises with each extra option.

**Comment by luohuazhiyu** [comment]
@Tornhoof Thank you very much. You are really efficient.

**Comment by Tornhoof** [comment]
Performance wise it should be a bit faster than the string version. 
If my tests work properly, 1.0.2 on Nuget should contain all the necessary bits to get this running.

**Comment by Tornhoof** [comment]
1.0.3's Asp.NET Core formatter package now contains the extension method AddSpanJson for the formatters, this configures SpanJson to use IncludeNulls, CamelCase and Integer Enums, as this is apparently the default for ASP.NET Core 2.1 with Json.NET.
I never realized that integer enums are the default for JSON.NET, I haven't used the default formatter for a long long time, always used Jil.
