### ISSUE TITLE
DateTimeParser doesn't handle negative offsets well - the sign of the minutes is not set correctly.

### ISSUE THREAD

**Issue by zlatanov** [Tornhoof/SpanJson#37]
https://github.com/Tornhoof/SpanJson/blob/1b17092305048b5181b519b2329f0a3dfd7484da/SpanJson/Helpers/DateTimeParser.Utf8.cs#L345-L346

On line 345 the negative sign of the hours is correctly handled but the same thing must be done for the minutes as well. Try serializing and then deserializing the following:

```csharp
new DateTimeOffset( 2016, 3, 5, 15, 57, 30, TimeSpan.FromMinutes( -90 ) )
```

When deserialized offset minutes will be 30 and offset hours will be -1 which will expand into:

```csharp
new TimeSpan( -1, 30, 0 );
```
Which in turn basically means "00:30:00". I am happy to submit a pull request if you confirm the issue.

**Comment by Tornhoof** [comment]
Thank you for reporting this bug. Yes I can confirm that it does not work as expected.

I'd be happy to accept a pull request.
Please fix it in both the utf8 version and the utf16 version and extend the DateTests with an appropriate test case.
