### ISSUE TITLE
Add Unsafe Api to directly return ArrayPool array

### ISSUE THREAD

**Issue by Tornhoof** [Tornhoof/SpanJson#44]
The following API could be added to return the array from the arraypool directly, instead of making a copy first.
This API will help cases where the caller might continue working with that array, e.g. copy/write it somewhere else.
The caller will need to return the array to the arraypool himself.

```csharp
public static ArraySegment<byte> SerializeUnsafe<T>(T value); // 1. variant
// and others
```
Which type should be used for the returned array, we need the array, the offset and the length.
* Span<T>: Afaik, there is no way to get the array back from a ``span``
* ReadOnlySpan<T>: Afaik, there is no way to get the array back from a ``span``, ReadOnly might not be the correct choice if the caller wants further modify the array.
* ReadOnlyMemory<T>: There is MemoryMarshal.TryGetArray (which returns an ArraySegment), ReadOnly might not be the correct choice if the caller wants further modify the array.
* ArraySegment<T>: Best fit in my opinion.

Any better ideas?

**Comment by benaadams** [comment]
Return type would need to be `ArraySegment` you don't want extra hoops to jump though to get the array which you have to return to the pool; since it needs to be always done.

Name probably should be more explicit? 
```csharp
ArraySegment<byte> SerializeToArrayPool<T>(T value)
```

**Comment by Tornhoof** [comment]
Thanks, good idea with a more explicit name.
