### ISSUE TITLE
IEnumerable of T ,IReadOnlyCollection of T and other generic collection interfaces support

### ISSUE THREAD

**Issue by dv00d00** [Tornhoof/SpanJson#48]
Why is it not possible to deserialize these?

**Comment by Tornhoof** [comment]
Short answer: I never needed them.

Long answer:
Let's take a look at ``IEnumerable<T>``, which type would you use for deserialization?, ``List<T>`` most probably.
But then the original type could have been ``Stack<T>`` and the behaviour would be wrong, JSON.NET still deserializes a stack in the wrong order afaik. The same applies to ``ISet<T>`` more or less, just with e.g. ``HashSet<T>``. I wanted to sidestep those issues.

The case gets, admittingly,  a bit less muddy for ``IReadOnlyCollection<T>`` and ``ICollection<T>``.

Personally I'd say that Json Serializers should be used with transfer objects and those are usually designed for it, i.e. no HashSet, Stack, Queue or similar etc.

**Comment by dv00d00** [comment]
In several 'enterprise' codebases I've been working on I often saw IEnumerable and IReadOnlyCollection on DTO. Just noticed it in our project I've been trying to use SpanJson, the fix was pretty trivial, but it could be a stopper for other peeps migrating. 

Is there a chance to add those, would gladly participate.

**Comment by Tornhoof** [comment]
I'll take a look and see what I can add or accept as a PR to the codebase.

**Comment by Tornhoof** [comment]
Most of the normal ``IEnumerable<T>`` types, i.e. IReadOnlyCollection, Collection etc. are now supported, I still block `` Stack<T>`` and ``ConcurrentStack``  due to the order problems.

**Comment by argentini** [comment]
@Tornhoof I've read through several issues and examples. For some reason my object will not deserialize a List<T> property. It serializes fine but the list is null when I deserialize. What would prevent the list from deserializing?

**Comment by Tornhoof** [comment]
The most common mistake is incompatible property casing, SpanJson is in the default configuration case sensitive.
