### ISSUE TITLE
Incorrect serialization behavior for long.MinValue

### ISSUE THREAD

**Issue by mburbea** [Tornhoof/SpanJson#5]
The `WriteUtf*Int64Internal` internal method special case for long.MinValue, but they do not return early. and so it will write the long.MinValue and then it will -long.MinValue.
So this object:
```class Q{
        public long Long {get;set;} = long.MinValue;
}
```
will serialize to the following json `{"Long":-92233720368547758089223372036854775808}`
You can see the bug here::
https://github.com/Tornhoof/SpanJson/blob/master/SpanJson/JsonWriter.Utf16.cs#L51

The special case is actually unnecessary and you can simplify the code. Even though negating it does nothing, casting it to ulong yields the correct value.
```cs
        public void WriteUtf16(long value)
        {
            ref var pos = ref _pos;
            if (value < 0)
            {
                if (pos > _chars.Length - 1)
                {
                    Grow(1);
                }

                _chars[pos++] = '-';
                value = unchecked(-value);
            }

            WriteUtf16((ulong)value);
      }
```

**Comment by Tornhoof** [comment]
Thank you for reporting this. I will fix this and publish a new version.

**Comment by Tornhoof** [comment]
The new version is https://www.nuget.org/packages/SpanJson/0.1.0-rc1-4
