### ISSUE TITLE
Question: How to decorate types on serialization with additional properties?

### ISSUE THREAD

**Issue by Montrichard** [Tornhoof/SpanJson#57]
I raised this question on Utf8Json but no reply. https://github.com/neuecc/Utf8Json/issues/117

I was wondering if it's possible with this serializer?

I've tried taking the object, converting to dynamic or dictionary but then realised the serializer doesn't cameCase the dictionary keys.

**Comment by Tornhoof** [comment]
The long route is using a customFormatter as described in https://github.com/Tornhoof/SpanJson/blob/master/SpanJson.Tests/CustomSerializerTests.cs, I highly recommend not going this route, as you actually need to handle all properties yourself.

The easiest way to achieve this is something like the codesnippet in the details below, you derive your object from DynamicObject and add your extra properties in the proper casing to an internal dictionary.
The result then looks like:
```json
{
	"@id": 5,
	"@type": "MyType",
	"value": "Hello World"
}
```

<details>

```csharp
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq.Expressions;
using SpanJson;
using SpanJson.Resolvers;

namespace ConsoleApp14
{
    class Program
    {
        static void Main(string[] args)
        {
            var myStuff = new MyTestDTO {Value = "Hello World"};
            myStuff.Add("@id", 5);
            myStuff.Add("@type", "MyType");

            var text = SpanJson.JsonSerializer.Generic.Utf16.Serialize<MyTestDTO, ExcludeNullsCamelCaseResolver<char>>(myStuff);

            var deserialized = SpanJson.JsonSerializer.Generic.Utf16.Deserialize<MyTestDTO, ExcludeNullsCamelCaseResolver<char>>(text);
        }

        public class MyTestDTO : DynamicObject
        {
            public string Value { get; set; }

            private readonly Dictionary<string, object> _dictionary = new Dictionary<string, object>();

            public override IEnumerable<string> GetDynamicMemberNames()
            {
                return _dictionary.Keys;
            }

            public override bool TryGetMember(GetMemberBinder binder, out object result)
            {
                if (_dictionary.TryGetValue(binder.Name, out result))
                {
                    return true;
                }

                return base.TryGetMember(binder, out result);
            }

            public override bool TrySetMember(SetMemberBinder binder, object value)
            {
                _dictionary[binder.Name] = value;
                return true;
            }

            public void Add(string key, object value)
            {
                _dictionary.Add(key, value);
            }
        }
    }
}

```
</details>

**Comment by Montrichard** [comment]
Thanks, that's similar to what I tried yesterday with the other serializer but will give this a go.

You show in the sample you have a DTO with a Value property then add id and type. In the json snippet it appears as @id, @type, value. Is there some ordering logic that can be manipulated as Ifrom my experience it would actually end up with Value, @id, @type . I did look at having a `List<KeyValuePair<string,object>>` to put entries at a specific index but it became a bit nasty. 

Thanks

**Comment by Tornhoof** [comment]
The order is not really defined, as in JSON the order of attributes is not defined.
Currently it's mainly the order of declaration and in the case above the order the dictionary returns.
I once played around with code evaluating the ``[DataMember(Order=1)]`` attribute, but that never made it into the code and in your case wouldn't help.
I'm sorry, I don't think you'll get an defined order without relying on obscure implementation details.

**Comment by Montrichard** [comment]
If one used the DynamicObject approach would the property names on the DTO be camelCased automatically or would you need DataMember attributes eg

```
 public class MyTestDTO : DynamicObject
        {
            [DataMember(Name="firstName"}]
            public string FirstName { get; set; }

            private readonly Dictionary<string, object> _dictionary = new Dictionary<string, object>();

            public override IEnumerable<string> GetDynamicMemberNames()
            {
                return _dictionary.Keys;
            }

            public override bool TryGetMember(GetMemberBinder binder, out object result)
            {
                if (_dictionary.TryGetValue(binder.Name, out result))
                {
                    return true;
                }

                return base.TryGetMember(binder, out result);
            }

            public override bool TrySetMember(SetMemberBinder binder, object value)
            {
                _dictionary[binder.Name] = value;
                return true;
            }

            public void Add(string key, object value)
            {
                _dictionary.Add(key, value);
            }
        }
```

**Comment by Montrichard** [comment]
Ah I see I can using the `var result = JsonSerializer.NonGeneric.Utf16.Serialize<ExcludeNullsCamelCaseResolver<char>>(dic);` approach would work

**Comment by Tornhoof** [comment]
As described in #58, to optimize your access problem you can try something like this, using fast-member by marc gravell, if you also care about deserialization it gets complicated very very fast.
```csharp
            var payload = new Payload {Value = "test"};
            Wrapper<Payload> wrapper = new Wrapper<Payload>(payload) {FirstName = "Value"};
            var output = SpanJson.JsonSerializer.Generic.Utf16
                .Serialize<Wrapper<Payload>, ExcludeNullsCamelCaseResolver<char>>(wrapper);
```

```csharp
    public class Wrapper<T> : DynamicObject where T : class, new()
    {
        [DataMember(Name = "firstName")]
        public string FirstName { get; set; }

        private readonly T _value;
        private static readonly FastMember.TypeAccessor Accessor;
        private static readonly string[] MemberNames;

        static Wrapper()
        {
            Accessor= TypeAccessor.Create(typeof(T));
            MemberNames = Accessor.GetMembers().Select(a => a.Name).ToArray();
        }
        public Wrapper(T value)
        {
            _value = value;
        }

        public override IEnumerable<string> GetDynamicMemberNames()
        {
            return MemberNames;
        }


        public override bool TryGetMember(GetMemberBinder binder, out object result)
        {
            if (MemberNames.Contains(binder.Name))
            {
                result =  Accessor[_value, binder.Name];
                return true;
            }
            return base.TryGetMember(binder, out result);
        }
    }
```

**Comment by Montrichard** [comment]
Thanks, will have a play over the weekend!

**Comment by Montrichard** [comment]
Just got to this, sorry.

I have a method like this:

```
    public Func<object, SerializationOptions, Stream, Task> GetHydraFunc(IMetaModelRepository _models)
    {
      return async (entity, options, stream) => 
      {
            //serialise here
      }
    }
```

As you can see it takes an object to serialize and doesn't have knowledge of the type, so creating a `Wrapper<T>` will be tricky.  Any ideas? Thanks again

**Comment by Montrichard** [comment]
I did try the Wrapper approach with Utf8Json just to see if it would work in a test app with a generic type passed in but it didn't

**Comment by Tornhoof** [comment]
You don't need a typed wrapper, you can simply use an untyped one, just create the ``TypeAccessor`` and ``MemberNames`` in the instance constructor and remove the generic type and the statics and replace ``T _value`` with ``object value``. You might want to measure the actual overhead of recreating the ``TypeAccessor`` and ``MemberNames`` Array in each object though.

There is nothing dependent on the generic type in the above example, fast-member by Marc Gravell works just fine without it.

**Comment by Montrichard** [comment]
I tried this but it didn't serialize the `object` passed in. It only serialized the properties on the Wrapper object

```
  public class Wrapper : DynamicObject
  {
    [DataMember(Name = "@id")]
    public string Id { get; set; }

    [DataMember(Name = "@context")]
    public string  Context { get; set; }

    [DataMember(Name = "@type")]
    public string Type { get; set; }

    private readonly object _value;
    private static readonly FastMember.TypeAccessor Accessor;
    private static readonly string[] MemberNames;

    static Wrapper()
    {
      Accessor= TypeAccessor.Create(typeof(object));
      MemberNames = Accessor.GetMembers().Select(a => a.Name).ToArray();
    }
    public Wrapper(object value)
    {
      _value = value;
    }

    public override IEnumerable<string> GetDynamicMemberNames()
    {
      return MemberNames;
    }


    public override bool TryGetMember(GetMemberBinder binder, out object result)
    {
      if (MemberNames.Contains(binder.Name))
      {
        result =  Accessor[_value, binder.Name];
        return true;
      }
      return base.TryGetMember(binder, out result);
    }
  }


```

**Comment by Tornhoof** [comment]
You still init Accessor and MemberNames in the static constructor from type(object), you need to initialize it from the real type, i.e. 
```csharp
    public Wrapper(object value)
    {
      _value = value;
      _accessor= TypeAccessor.Create(value.GetType()));
      _memberNames = Accessor.GetMembers().Select(a => a.Name).ToArray();
    }
```

**Comment by Montrichard** [comment]
Ah thanks! Still no luck using Utf8Json though, would you expect that to work?. Realised last night SpanJson targets netcoreapp2.1 directly which I don't think I can use but will reassess.

**Comment by Montrichard** [comment]
Thanks! Just tried Jil and no luck, works great with SpanJson though 😄

**Comment by Montrichard** [comment]
Ah, is there a way with SpanJson and the wrapper approach for it to get the DataMember values of the type passed into the ctor?

**Comment by Tornhoof** [comment]
you mean id, type, context? Just put them in the constructor, as long as you don't care about deserialization you can put as much as you like into the ctor.

**Comment by Montrichard** [comment]
No sorry, I mean the DataMember values of the entity passed in

```
    public class Person
    {
        [DataMember(Name = "YearsOld")]
        public int Age { get; set; }
    }
```

**Comment by Montrichard** [comment]
I've got something like this but my linq is failing me

```
 var atts = value.GetType().GetProperties().Select(p => p.CustomAttributes).First(f=>f.Where(n=>n.NamedArguments.First(x=>x.MemberName == "Name")).Select(y=>y.TypedValue.Value.ToString()));
           
```

**Comment by Montrichard** [comment]
Ah have it now with:

` var atts = value.GetType().GetProperties().SelectMany(p => p.CustomAttributes).SelectMany(g=>g.NamedArguments).Where(c=>c.MemberName == "Name").Select(v=>v.TypedValue.Value.ToString());`

But now realised I have to get the properties that don't have the attribute too.

What fun ;)

**Comment by Montrichard** [comment]
```

var atts = value.GetType().GetProperties().SelectMany(p => p.CustomAttributes).SelectMany(g=>g.NamedArguments).Where(c=>c.MemberName == "Name").Select(v=>v.TypedValue.Value.ToString());

            var others = value.GetType().GetProperties().Where(x => x.CustomAttributes.All(y => y.AttributeType != typeof(DataMemberAttribute))).Select(c=>c.Name);


            var result = atts.Concat(others);
            
```

**Comment by Tornhoof** [comment]
I think you're completely on the wrong track at the moment.
You need to understand the capabilities of the dynamic runtime in .NET.
That DynamicObject approach from above can delivier you properties in every kind of formatting you want, including support for Jil etc. (That's why suggested JIL).
The ``GetDynamicMemberNames`` returns the known properties, if you put there your own propertyname and you remove the public property of ``id`` etc. you can control it as much as you like.

See the example below:
<details>
        static void Main(string[] args)
        {
            var payload = new Payload { Value = "test" };

            var wrapper = new Wrapper<Payload>(payload, "My Name");
            var text = JSON.SerializeDynamic(wrapper, Options.ExcludeNullsCamelCase);
        }

        public class Payload
        {
            public string Value { get; set; }
        }

        public class Wrapper<T> : DynamicObject where T : class, new()
        {
            private string m_FirstName;

            private readonly T _value;
            private static readonly FastMember.TypeAccessor Accessor;
            private static readonly List<string> MemberNames;

            static Wrapper()
            {
                Accessor = TypeAccessor.Create(typeof(T));
                MemberNames = Accessor.GetMembers().Select(a => a.Name).ToList();
                MemberNames.Add("firstName");
            }
            public Wrapper(T value, string name)
            {
                _value = value;
                m_FirstName = name;
            }

            public override IEnumerable<string> GetDynamicMemberNames()
            {
                return MemberNames;
            }


            public override bool TryGetMember(GetMemberBinder binder, out object result)
            {
                switch (binder.Name)
                {
                    case "firstName":
                    {
                        result = m_FirstName;
                        return true;
                    }
                    default:
                        if (MemberNames.Contains(binder.Name))
                        {
                            result = Accessor[_value, binder.Name];
                            return true;
                        }

                        break;
                }

                return base.TryGetMember(binder, out result);
            }
        }
</detail>

**Comment by Montrichard** [comment]
I don't think that will work though as the Accessor is going to use the public properties names to get the value out

**Comment by Tornhoof** [comment]
Well then you need to handle it yourself and change the datamembers etc. yourself.
You might want to look at something else maybe, either use codegeneration or use a library like Castle Proxy to create dynamic types which then represent your wrapper, i.e. by dynamically creating a derived type of the payload type and adding the properties you want yourself.
I imagine you will need to understand quite a few more aspects of the CLR to do that though.
