### ISSUE TITLE
camelCase Dictionary keys

### ISSUE THREAD

**Issue by Montrichard** [Tornhoof/SpanJson#58]
Is this possible?

**Comment by Tornhoof** [comment]
There are no individual, i.e. user configurable settings for specific formatters, that would be required for this.
Anyway, automatically converting Dictionary Keys to camelCase is in my opinion the wrong approach, a Dictionary is commonly something you have full control over, including the keys, its types etc.
The approach from your other issue #57  is the right one if you want to add ``dynamic`` properties, as these are returned from the DLR and are getting processed by the camel case logic then.

**Comment by Montrichard** [comment]
Problem is I'm trying to do it on any objects passed into my lib so I can't expect users of my lib to make their DTOs implement DynamicObject so Im going to have to GetPropertyInfo and loop over the properties and add to a dictionary and then add the additional properties I want, then camel case the keys.

If you have any other idea it would be greatly appreciated 😄

**Comment by Tornhoof** [comment]
I see, let me think a bit about that problem.

**Comment by Tornhoof** [comment]
No I don't think there is an easy solution to that problem, to simplify your problem and especially if you only care about serialization and not deserialization, you can optimize the code from #57 and use a library like fast-member to improve it., I'll post a snippet for that on the other issue.
