### ISSUE TITLE
Plans for 2.0

### ISSUE THREAD

**Issue by Tornhoof** [Tornhoof/SpanJson#69]
**Breaking Changes**
- Strong Naming is a breaking change.
- removing NestingLimit from the API and using a property in the writer is a breaking change.

**Features**
- Evaluate if #61 is possible.

**Comment by dimaaan** [comment]
Hi @Tornhoof 
Thanks for the great work!
Can you add serialization/deserialization overloads to pass struct be reference?
Something like this:
```cs
byte[] Serialize<T>(in T input) where T: struct;
```
```cs
bool TryDeserialize<T>(byte[] input, out T result) where T: struct;
```

**Comment by Tornhoof** [comment]
Hi  @dimaaan 
Thank you for your suggestion.
Using ``in`` as a modifier for structs only works well for ``readonly structs``, otherwise you'll always get a  defensive struct copy. See https://blogs.msdn.microsoft.com/seteplia/2018/03/07/the-in-modifier-and-the-readonly-structs-in-c/ for a more detailed explanation (with benchmarks).
Simply said, your API suggestion above for ``Serialize`` will most likely be slower for most of the structs.

As for deserialization, this is not just about the top-level methods, but would need propagate down into the actual codegen logic and that's additional complexity I'm not willing to add without extensive benchmarks.

**Comment by Tornhoof** [comment]
I think that's it, #90 had the last few cleanup tasks in it and the upgrade guide: https://github.com/Tornhoof/SpanJson/wiki/Upgrade-Guide describes the necessary changes for those using affected functionality.
