### ISSUE TITLE
Incorrect serialization of surrogate pairs when writing utf8. 

### ISSUE THREAD

**Issue by mburbea** [Tornhoof/SpanJson#7]
The current implementation handles values in ucs2, but cannot handle surrogate pairs.
The code is currently is encoding each pair as a separate code point and as a result is not handling correctly. 
Thus `"💩"` will serialize as the following `"��"`.

You can detect surrogate pair with the following logic::
```cs
(uint)c - 0xD800u < 0x0800u
```
(changed the constant, the range for surrogate its 0xD800-0xDFFF).
I think it is safe to assume that a high surrogate pair character always is followed by a low surrogate pair character, so you can probably avoid testing both as malformed utf16, will only encode to malformed utf8.

**Comment by Tornhoof** [comment]
Thank you for reporting this. I will fix this is asap

**Comment by Tornhoof** [comment]
I'll publish https://www.nuget.org/packages/SpanJson/0.1.0-rc1-5 with the fix.
I have to rerun the benchmarks again to get an idea about of the performance impact, as I found a related bug with the unescaping logic.
