### ISSUE TITLE
JsonParserException: 'Error Reading JSON data: 'ExpectedDoubleQuote' at position: X

### ISSUE THREAD

**Issue by dimaaan** [Tornhoof/SpanJson#75]
This works OK:
```cs
JsonSerializer.Generic.Utf8.Deserialize<Dictionary<string, object>>(System.Text.Encoding.UTF8.GetBytes(@"{""a"": 1,""b"": ""2""}"));
```
But this fails:
```cs
JsonSerializer.Generic.Utf8.Deserialize<Dictionary<string, object>>(System.Text.Encoding.UTF8.GetBytes(@"{""a"": 1, ""b"": ""2""}"));
```
In case i add space after "1," the above exception is thrown.

Expected behavior:
insignificant spaces should be skipped without an error

**Comment by Tornhoof** [comment]
Thank you for reporting this bug.
I can confirm that it is not properly skipping the whitespace in the dictionary deserializer.

**Comment by Tornhoof** [comment]
I'll push a V1.3.3 with the fix in a few minutes, which should contain the fix. I just need to figure out how to build/deploy from a branch first.
