### ISSUE TITLE
Improve JsonWriter<TSymbol>.WriteUtf(8|16)String methods

### ISSUE THREAD

**Issue by dimaaan** [Tornhoof/SpanJson#87]
**Suggestion**

Change `WriteUtf8String` and `WriteUtf16String` methods signature from:
```cs
public void WriteUtf8String(string value)
```
to
```cs
public void WriteUtf8String(ReadOnlySpan<char> value)
```

**Reason**

I have a complicated object graph that can not be handled by `ComplexFormatter` in the way i want it, so i implement `ICustomJsonFormatter<T>` to handle it. 
Inside my custom formatter i need to write `ReadOnlySpan<char>` onto writer buffer.
Currently, the only way to do that, is to allocate new string, which is not acceptable for me, because is causes GC pauses on hi load.

In my local copy of `SpanJson` i did that with just a few lines changed and it seems it works fine.

**Comment by Tornhoof** [comment]
Thanks for suggesting this. Yes, I think that's fine to change.
