### ISSUE TITLE
CustomFormatters for Nullable structs not working properly

### ISSUE THREAD

**Issue by Tornhoof** [Tornhoof/SpanJson#97]
As reported in PR #96, the code for the optimized skip-null path is not checking for custom formatters.

**Comment by mstyura** [comment]
> then I highly recommend annotating CustomStruct itself with the JsonConverter directly,

Wow, that's awesome! I didn't get this from samples I've seen in README. Thank you very much for quick response!

**Comment by Tornhoof** [comment]
This is fixed in 2.0.3
